services:
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_app
    volumes:
      - .env:/var/www/.env
      - ./bin:/var/www/bin
      - ./config:/var/www/config
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./test:/var/www/test
      - ./vendor:/var/www/vendor
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db
    working_dir: /var/www/html
    command: >
      sh -c "php -S 0.0.0.0:80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DBNAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge